#
# Build stage
#
FROM maven:3.8.5-openjdk-17 AS build-stage
COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean -DskipTests package

#
# Package stage
#
FROM openjdk:19-jdk-oracle
COPY --from=build-stage /home/app/target/api-demo-0.0.1-SNAPSHOT.jar /usr/local/lib/api.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/usr/local/lib/api.jar"]