apiVersion: v1
kind: Secret
metadata:
  name: app-db-qa
type: Opaque
data:
  # MYSQL_DATABASE: YXBpLWRlbW8tZGItcWE=
  MYSQL_PASSWORD: MTIzNHF3ZXI=
  MYSQL_ROOT_PASSWORD: cm9vdDE=
  MYSQL_USER: dXNlcg==
stringData:
  MYSQL_DATABASE: "{{ .Values.appDatabase.name }}-{{ .Values.global.environment }}"
  # MYSQL_PASSWORD: 1234qwer
  # MYSQL_ROOT_PASSWORD: root1
  # MYSQL_USER: user