apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-out.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: app-server
  name: app-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-out.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: app-server
    spec:
      containers:
        - image: "{{ .Values.appServer.image.repository }}:{{ .Values.appServer.image.tag }}"
          name: app-server
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-server-config
          resources: {}
      restartPolicy: Always
status: {}
